# Generated by Django 3.2.5 on 2022-07-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=150)),
                ('Last_name', models.CharField(max_length=150)),
                ('Date_Of_Birth', models.DateField(verbose_name='Date Of Birth')),
                ('Gender', models.CharField(max_length=15)),
                ('Address', models.TextField(verbose_name='Address')),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('PINCODE', models.IntegerField(max_length=6)),
                ('Mobile_number', models.IntegerField(max_length=10)),
            ],
        ),
    ]
