# Generated by Django 3.2.5 on 2022-07-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='First_name',
            field=models.CharField(max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='reg',
            name='Last_name',
            field=models.CharField(max_length=150, verbose_name='Last Name'),
        ),
    ]
